### ISSUE TITLE
OpenCL 3.0

### ISSUE THREAD

**Issue by gwawiork** [OCL-dev/ocl-icd#13]
Hi
Do you have any plans with release for OpenCL 3.0. For today state of OpenCL 3.0 specification is provisional so some changes could appear. However nice to have "provisional release package"

**Comment by Kerilk** [comment]
I am looking into it.

**Comment by gwawiork** [comment]
Ok thanks. 
The three new API function where committed here:
clCreateImageWithProperties/clCreateBufferWithProperties
https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/23475bd123d43d2087323962344457fe4a0fb13c 

clSetContextDestructorCallback
https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/c7622e6f6f3825ec24cb87bfeea2fd8deb15053b

For today to build new ICD with these functions from Khronos repository you need to add -DENABLE_OPENCL30_PROVISIONAL=1 while generation solution

**Comment by Kerilk** [comment]
Support for those was added to ocl-icd here:
[OCL-dev/ocl-icd@e9c19dc](https://github.com/OCL-dev/ocl-icd/commit/e9c19dc8a65de8f8cb758a0a2f964785adcb27d9)
and there:
[OCL-dev/ocl-icd@cbf56ca](https://github.com/OCL-dev/ocl-icd/commit/cbf56cad71f890686ac922db86fda962f2f938a6)

I am reluctant to create a release with those changes as long as one of those entry points could be removed from the dispatch table, because it would break backward compatibility for applications built against this release. You can still build the loader from sources if you need it. I didn't find any issue with it. The v3.0 will be released as soon as the specification is officially adopted.

**Comment by gwawiork** [comment]
Thanks a lot. I did not notice these commits !
